# Generated by Django 5.2.9 on 2025-12-28 00:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('somme_remise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Somme remise')),
                ('nom_depense', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la dépense')),
                ('somme_depense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Somme dépensée')),
                ('somme_restante', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Somme restante')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Dépense employé',
                'verbose_name_plural': 'Dépenses employés',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
