# Generated by Django 5.2.9 on 2026-02-05 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs autorisés à voir ce tableau lorsque celui-ci est privé.', related_name='employees_with_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Si coché, le tableau de cet employé est visible uniquement par certains utilisateurs.'),
        ),
    ]
