# Generated by Django 5.2.9 on 2026-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_allowed_users_employee_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si décoché, le tableau de cet employé est désactivé et masqué pour tous les utilisateurs.'),
        ),
    ]
