# Generated by Django 5.2.9 on 2026-02-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeexpense_tonnage_prix'),
        ('employees', '0003_employee_is_active'),
    ]

    operations = [
    ]
