# Generated by Django 5.2.9 on 2026-01-13 10:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_alter_customer_email'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('nom_client', models.CharField(help_text='Nom du client (si non enregistré)', max_length=255, verbose_name='Nom du client')),
                ('nom_produit', models.CharField(help_text='Nom du produit (si non enregistré)', max_length=255, verbose_name='Nom du produit')),
                ('quantite_kg', models.DecimalField(decimal_places=2, help_text='Quantité en kilogrammes', max_digits=10, verbose_name='Quantité (kg)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix par kilogramme', max_digits=10, verbose_name='Prix unitaire (FCFA/kg)')),
                ('somme_totale', models.DecimalField(decimal_places=2, help_text='Quantité × Prix unitaire', max_digits=12, verbose_name='Somme totale')),
                ('charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charges additionnelles', max_digits=12, verbose_name='Charge')),
                ('somme_net', models.DecimalField(decimal_places=2, help_text='Somme totale - Charge', max_digits=12, verbose_name='Somme nette')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles (optionnel)', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='customers.customer', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_created', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
