# Generated by Django 5.2.9 on 2026-01-13 12:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_email'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='somme_net',
        ),
        migrations.AddField(
            model_name='achat',
            name='gros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantité en gros', max_digits=10, verbose_name='Gros'),
        ),
        migrations.AddField(
            model_name='achat',
            name='unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantité en unités', max_digits=10, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='nom_client',
            field=models.CharField(blank=True, help_text='Nom du client (si non enregistré)', max_length=255, verbose_name='Nom du client'),
        ),
        migrations.CreateModel(
            name='EntreeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entree', models.CharField(help_text="Numéro unique de l'entrée", max_length=50, unique=True, verbose_name="Numéro d'entrée")),
                ('date', models.DateField(verbose_name='Date')),
                ('nom_client', models.CharField(help_text='Nom du client (si non enregistré)', max_length=255, verbose_name='Nom du client')),
                ('transport', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coûts de transport', max_digits=12, verbose_name='Transport')),
                ('autres_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Autres charges additionnelles', max_digits=12, verbose_name='Autres charges')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_achat', to='customers.customer', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_achat_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'achat",
                'verbose_name_plural': "Entrées d'achat",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='achat',
            name='entree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='purchases.entreeachat', verbose_name="Entrée d'achat"),
        ),
    ]
