# Generated by Django 5.2.9 on 2026-01-13 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_achat_charge_remove_achat_somme_net_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreeachat',
            name='autres_charges',
        ),
        migrations.RemoveField(
            model_name='entreeachat',
            name='transport',
        ),
        migrations.AddField(
            model_name='entreeachat',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charges additionnelles', max_digits=12, verbose_name='Charge'),
        ),
    ]
