# Generated by Django 5.2.9 on 2026-01-14 01:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_entreeachat_autres_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreeachat',
            name='charge',
        ),
        migrations.AddField(
            model_name='entreeachat',
            name='autres_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Autres charges additionnelles', max_digits=12, verbose_name='Autres charges'),
        ),
        migrations.AddField(
            model_name='entreeachat',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Avance payée', max_digits=12, verbose_name='Avance'),
        ),
        migrations.AddField(
            model_name='entreeachat',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coûts de transport', max_digits=12, verbose_name='Transport'),
        ),
    ]
