# Generated by Django 5.2.9 on 2026-01-14 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_remove_entreeachat_charge_entreeachat_autres_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeachat',
            name='restant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant restant à ajouter', max_digits=12, verbose_name='Restant'),
        ),
    ]
