# Generated by Django 5.2.9 on 2026-01-17 16:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_entreeachat_restant'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeachat',
            name='paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant déjà payé', max_digits=12, verbose_name='Somme payée'),
        ),
    ]
