# Generated by Django 5.2.9 on 2026-01-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_entreeachat_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeachat',
            name='numero_entree',
            field=models.CharField(blank=True, help_text="Numéro unique de l'entrée (généré automatiquement si non fourni)", max_length=50, null=True, unique=True, verbose_name="Numéro d'entrée"),
        ),
    ]
