# Generated by Django 5.2.9 on 2025-12-05 01:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'entrée")),
                ('nom_fournisseur', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('type_denree', models.CharField(max_length=100, verbose_name='Type de denrée (Karité, Maïs, etc.)')),
                ('nombre_sacs', models.IntegerField(default=0, verbose_name='Nombre de sacs')),
                ('poids_par_sac', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Poids par sac (kg)')),
                ('tonnage_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tonnage total (kg)')),
                ('numero_magasin', models.CharField(choices=[('1', 'Magasin 1'), ('2', 'Magasin 2')], default='1', max_length=1, verbose_name='Numéro du magasin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée de stock',
                'verbose_name_plural': 'Entrées de stock',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
