# Generated by Django 5.2.9 on 2025-12-21 10:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamionChargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_chargement', models.DateField(verbose_name='Date du chargement')),
                ('numero_camion', models.CharField(blank=True, max_length=100, verbose_name='Numéro du camion')),
                ('type_denree', models.CharField(max_length=100, verbose_name='Type de denrée (Karité, Maïs, etc.)')),
                ('nombre_sacs', models.IntegerField(default=0, verbose_name='Nombre de sacs')),
                ('poids_par_sac', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Poids par sac (kg)')),
                ('tonnage_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tonnage total (kg)')),
                ('numero_magasin', models.CharField(choices=[('1', 'Magasin 1'), ('2', 'Magasin 2')], default='1', max_length=1, verbose_name='Numéro du magasin')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Destination')),
                ('chauffeur', models.CharField(blank=True, max_length=200, verbose_name='Chauffeur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camion_chargements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chargement de camion',
                'verbose_name_plural': 'Chargements de camion',
                'ordering': ['-date_chargement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargementStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sacs_utilises', models.IntegerField(default=0, verbose_name='Nombre de sacs utilisés')),
                ('chargement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='stock.camionchargement')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargements', to='stock.stockentry')),
            ],
            options={
                'verbose_name': 'Article de stock pour chargement',
                'verbose_name_plural': 'Articles de stock pour chargement',
                'unique_together': {('chargement', 'stock_entry')},
            },
        ),
    ]
