# Generated by Django 5.2.9 on 2025-12-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_camionchargement_chargementstockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='type_operation',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], default='entree', max_length=10, verbose_name="Type d'opération"),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='date',
            field=models.DateField(verbose_name="Date d'opération"),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='nom_fournisseur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du fournisseur/client'),
        ),
    ]
