# Generated by Django 5.2.9 on 2025-12-26 23:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_add_type_operation_to_stock_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionchargement',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée"),
        ),
        migrations.AddField(
            model_name='camionchargement',
            name='numero_chauffeur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Numéro de chauffeur'),
        ),
        migrations.AddField(
            model_name='camionchargement',
            name='poids_arrive',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Poids arrivé (kg)'),
        ),
        migrations.AddField(
            model_name='camionchargement',
            name='ville_depart',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ville de départ'),
        ),
        migrations.AlterField(
            model_name='camionchargement',
            name='numero_camion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de camion'),
        ),
        migrations.AlterField(
            model_name='camionchargement',
            name='poids_par_sac',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Poids de chaque sac (kg)'),
        ),
        migrations.AlterField(
            model_name='camionchargement',
            name='tonnage_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tonnage (kg)'),
        ),
        migrations.AlterField(
            model_name='camionchargement',
            name='type_denree',
            field=models.CharField(max_length=100, verbose_name='Type de produits'),
        ),
    ]
