# Generated by Django 5.2.9 on 2025-12-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_add_camion_chargement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionchargement',
            name='numero_magasin',
            field=models.CharField(choices=[('1', 'Djaradougou'), ('2', 'Ouezzin-ville'), ('3', 'Bamako')], default='1', max_length=20, verbose_name='Numéro du magasin'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='numero_magasin',
            field=models.CharField(choices=[('1', 'Djaradougou'), ('2', 'Ouezzin-ville'), ('3', 'Bamako')], default='1', max_length=20, verbose_name='Numéro du magasin'),
        ),
    ]
