# Generated by Django 5.2.9 on 2026-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_camionchargement_numero_magasin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Charges ou coûts additionnels', max_digits=12, null=True, verbose_name='Charges (FCFA)'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Prix unitaire ou prix total', max_digits=12, null=True, verbose_name='Prix (FCFA)'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='sommes',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant total', max_digits=12, null=True, verbose_name='Sommes (FCFA)'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='sommes_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Sommes nettes (sommes - charges)', max_digits=12, null=True, verbose_name='Sommes net (FCFA)'),
        ),
    ]
