# Generated by Django 5.2.9 on 2026-01-13 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockentry_charges_stockentry_prix_stockentry_sommes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='sommes',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='sommes_net',
        ),
        migrations.CreateModel(
            name='CalculFinancierStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Prix unitaire ou prix total', max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('sommes', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant total', max_digits=12, null=True, verbose_name='Sommes (FCFA)')),
                ('charges', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Charges ou coûts additionnels', max_digits=12, null=True, verbose_name='Charges (FCFA)')),
                ('sommes_net', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Sommes nettes (sommes - charges)', max_digits=12, null=True, verbose_name='Sommes net (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculs_financiers_created', to=settings.AUTH_USER_MODEL)),
                ('stock_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calcul_financier', to='stock.stockentry', verbose_name='Entrée de stock')),
            ],
            options={
                'verbose_name': 'Calcul financier stock',
                'verbose_name_plural': 'Calculs financiers stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
