# Generated by Django 5.2.9 on 2026-01-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_stockentry_charges_remove_stockentry_prix_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculFinancierStock',
        ),
    ]
