# Generated by Django migration

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_delete_calculfinancierstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionchargement',
            name='depenses',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
                null=True,
                verbose_name='Dépenses encourues (FCFA)'
            ),
        ),
        migrations.AddField(
            model_name='camionchargement',
            name='benefices',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
                null=True,
                verbose_name='Bénéfices générés (FCFA)'
            ),
        ),
    ]

