# Generated by Django 5.2.9 on 2026-03-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_add_depenses_benefices_to_camionchargement'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionchargement',
            name='proprietaire',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proprietaire'),
        ),
    ]
