# Generated by Django 5.2.9 on 2026-01-10 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('nom_depense', models.CharField(max_length=255, verbose_name='Nom de la dépense')),
                ('somme', models.DecimalField(decimal_places=2, help_text='Montant de la dépense', max_digits=12, verbose_name='Somme')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles (optionnel)', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
