# Generated by Django 5.2.9 on 2026-01-23 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_index', models.IntegerField(help_text="Index de la dépense où s'arrête la période", verbose_name="Index d'arrêt")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_stops_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arrêt de compte',
                'verbose_name_plural': 'Arrêts de compte',
                'ordering': ['stop_index'],
            },
        ),
    ]
