# Generated by Django 5.2.9 on 2026-01-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_periodstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='nom_personne',
            field=models.CharField(blank=True, help_text='Nom de la personne concernée', max_length=255, verbose_name='Nom personne'),
        ),
    ]
