# Generated by Django 5.2.9 on 2026-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_set_default_nom_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='nom_personne',
            field=models.CharField(blank=True, default='', help_text='Nom de la personne concernée', max_length=255, verbose_name='Nom personne'),
        ),
    ]
