# Generated by Django 5.2.9 on 2026-02-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_argententry'),
    ]

    operations = [
        migrations.AddField(
            model_name='argententry',
            name='nom_boss',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du boss'),
        ),
    ]
