# Generated by Django 5.2.9 on 2026-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_argententry_nom_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='argententry',
            name='nom_sortie',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom sortie'),
        ),
        migrations.AddField(
            model_name='argententry',
            name='somme_sortie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant de la sortie d'argent", max_digits=12, null=True, verbose_name='Somme sortie'),
        ),
    ]
