# Generated by Django 5.2.9 on 2026-02-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_argententry_nom_sortie_argententry_somme_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='argententry',
            name='date_sortie',
            field=models.DateField(blank=True, null=True, verbose_name='Date sortie'),
        ),
    ]
