# Generated by Django 5.2.9 on 2026-02-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_argententry_date_sortie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argententry',
            options={'ordering': ['id'], 'verbose_name': "Entrée d'argent", 'verbose_name_plural': "Entrées d'argent"},
        ),
    ]
