# Generated by Django 5.2.9 on 2026-02-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_argententry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argententry',
            name='lieu_retrait',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lieu de retrait'),
        ),
        migrations.AlterField(
            model_name='argententry',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='argententry',
            name='somme',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant de l'entrée d'argent", max_digits=12, null=True, verbose_name='Somme'),
        ),
    ]
