# Generated by Django 5.2.9 on 2026-02-07 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_argententry_lieu_retrait_alter_argententry_nom_and_more'),
        ('argent', '0002_migrate_data_from_expenses'),  # Wait for data migration to complete
    ]

    operations = [
        migrations.DeleteModel(
            name='ArgentEntry',
        ),
    ]
