# Generated by Django 5.2.9 on 2026-02-07 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransiteurEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('numero_camion', models.CharField(blank=True, default='', help_text='Numéro du camion', max_length=255, verbose_name='N° Camion')),
                ('numero_chauffeur', models.CharField(blank=True, default='', help_text='Numéro du chauffeur', max_length=255, verbose_name='N° Chauffeur')),
                ('ville_depart', models.CharField(blank=True, default='', help_text='Ville de départ', max_length=255, verbose_name='Ville départ')),
                ('ville_arrivant', models.CharField(blank=True, default='', help_text="Ville d'arrivée", max_length=255, verbose_name='Ville arrivant')),
                ('depenses', models.DecimalField(blank=True, decimal_places=2, help_text='Dépenses du camion', max_digits=12, null=True, verbose_name='Dépenses')),
                ('argent_donne', models.DecimalField(blank=True, decimal_places=2, help_text='Argent donné au transitaire', max_digits=12, null=True, verbose_name='Argent donné')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transiteur_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée transiteur',
                'verbose_name_plural': 'Entrées transiteur',
                'ordering': ['id'],
            },
        ),
    ]
