# Generated by Django 5.2.9 on 2026-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transiteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transiteurentry',
            name='nom_produit',
            field=models.CharField(blank=True, default='', help_text='Nom du produit', max_length=255, verbose_name='Nom produit'),
        ),
    ]
