# Generated by Django 5.2.9 on 2025-12-06 14:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_chargement', models.DateField(verbose_name='Date du chargement')),
                ('nombre_sacs', models.IntegerField(default=0, verbose_name='Nombre de sacs')),
                ('poids', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Poids (kg)')),
                ('tonnage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tonnage (kg)')),
                ('prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix par kg')),
                ('somme_totale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Somme totale')),
                ('avance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Avance')),
                ('somme_restante', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Somme restante')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargements', to='customers.customer', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_chargements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chargement client',
                'verbose_name_plural': 'Chargements clients',
                'ordering': ['-date_chargement', '-created_at'],
            },
        ),
    ]
