# Generated by Django 5.2.9 on 2025-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_clientchargement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientchargement',
            name='nombre_sacs',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Nombre de sacs'),
        ),
        migrations.AlterField(
            model_name='clientchargement',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AlterField(
            model_name='clientchargement',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Prix par kg'),
        ),
        migrations.AlterField(
            model_name='clientchargement',
            name='somme_restante',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Somme restante'),
        ),
        migrations.AlterField(
            model_name='clientchargement',
            name='somme_totale',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Somme totale'),
        ),
        migrations.AlterField(
            model_name='clientchargement',
            name='tonnage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Tonnage (kg)'),
        ),
    ]
