# Generated by Django 5.2.9 on 2025-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_clientchargement_nombre_sacs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchargement',
            name='poids_sac_vide',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text="Poids d'un sac vide (généralement 0.5kg ou 1kg)", max_digits=10, null=True, verbose_name='Poids sac vide (kg)'),
        ),
    ]
