# Generated by Django 5.2.9 on 2026-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchargement',
            name='type_operation',
            field=models.CharField(choices=[('produit', 'Produit'), ('avance', 'Avance'), ('reglement', 'Règlement')], default='produit', max_length=20, verbose_name="Type d'opération"),
        ),
    ]
