# Generated by Django 5.2.9 on 2026-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_clientchargement_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchargement',
            name='nom_produit',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom du produit'),
        ),
    ]
