# Generated by Django 5.2.9 on 2026-02-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_clientchargement_nom_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchargement',
            name='n_camion',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro de camion'),
        ),
    ]
