# Generated by Django 5.2.9 on 2026-02-07 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('nom', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom')),
                ('nom_boss', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du boss')),
                ('lieu_retrait', models.CharField(blank=True, default='', max_length=255, verbose_name='Lieu de retrait')),
                ('somme', models.DecimalField(blank=True, decimal_places=2, help_text="Montant de l'entrée d'argent", max_digits=12, null=True, verbose_name='Somme')),
                ('nom_sortie', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom sortie')),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date sortie')),
                ('somme_sortie', models.DecimalField(blank=True, decimal_places=2, help_text="Montant de la sortie d'argent", max_digits=12, null=True, verbose_name='Somme sortie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='argent_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'argent",
                'verbose_name_plural': "Entrées d'argent",
                'ordering': ['id'],
            },
        ),
    ]
