# Generated by Django 5.2.9 on 2026-02-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0003_remove_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='argententry',
            name='lieu_retrait',
            field=models.CharField(blank=True, default='', help_text="Lieu où l'argent est retiré", max_length=255, verbose_name='Lieu de retrait'),
        ),
        migrations.AddField(
            model_name='argententry',
            name='nom_boss',
            field=models.CharField(blank=True, default='', help_text='Nom du boss', max_length=255, verbose_name='Nom du boss'),
        ),
        migrations.AddField(
            model_name='argententry',
            name='nom_recevant',
            field=models.CharField(blank=True, default='', help_text='Nom de la personne qui reçoit', max_length=255, verbose_name='Nom de Recevant'),
        ),
        migrations.AddField(
            model_name='argententry',
            name='nom_recuperant',
            field=models.CharField(blank=True, default='', help_text='Nom de la personne qui récupère', max_length=255, verbose_name='Nom de Récupérant'),
        ),
    ]
